name: Backend CI

on:
  pull_request:
    branches: [dev, main]

  push:
    branches: [dev, main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

  workflow_dispatch: # Permite acionamento manual

jobs:
  build-and-test:
    name: Backend Build & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      # Este passo verifica se arquivos no diretório do backend foram alterados.
      - name: Check for file changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**
            .github/workflows/backend-ci.yml

      - name: Checkout repository
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/checkout@v4

      - name: Check for file changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**
            .github/workflows/backend-ci.yml

      # Os passos seguintes só rodam se houver mudanças nos arquivos do backend.
      # A condição 'if' garante que o job termine com sucesso rapidamente se não houver nada a fazer.
      - name: Set up Python 3.12
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (and enforce 90% coverage)
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pytest --cov=. --cov-fail-under=90

      - name: Mark as successful if no files were changed
        if: steps.changed-files.outputs.any_changed == 'false'
        run: echo "No backend files changed. Skipping CI."
