name: CD - Build and Publish Docker Images

on:
  pull_request:
    paths:
      - "backend/**" # Inclui o cron que está dentro do backend
      - "frontend/**"
      - ".github/workflows/docker.yml"
  push:
    branches:
      - dev
      - main
    paths:
      - "backend/**" # Inclui o cron que está dentro do backend
      - "frontend/**"
      - ".github/workflows/docker.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define cada imagem como um item na matriz de estratégia
        # 'name' é o nome da imagem e 'context' é o diretório do Dockerfile
        include:
          - name: backend
            context: ./backend
          - name: frontend
            context: ./frontend
          - name: cron
            context: ./backend/cron

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Necessário para a detecção de alterações de caminho
          fetch-depth: 2

      # Passo para verificar se houve alterações no diretório da imagem atual da matriz
      - name: Check for changes in '${{ matrix.name }}' directory
        id: check_changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^${{ matrix.context }}/" || git diff --name-only HEAD~1 HEAD | grep -q "^\.github/workflows/docker\.yml$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in ${{ matrix.context }} directory. Skipping build."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check_changes.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: steps.check_changes.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker image
        if: steps.check_changes.outputs.changed == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.name }}

      - name: Build and push Docker image for ${{ matrix.name }}
        if: steps.check_changes.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          # Só faz push se o evento for um push em 'dev' ou 'main', não em um PR
          push: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Habilita o cache para acelerar builds futuros
          cache-from: type=gha
          cache-to: type=gha,mode=max
