name: Frontend CI (Build)

on:
  pull_request:
    branches: [dev, main]

  push:
    branches: [dev, main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"

  workflow_dispatch: # Permite acionamento manual dos workflows

jobs:
  build-and-test:
    name: Frontend Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      # Este passo verifica se arquivos no diret√≥rio do frontend foram alterados.
      - name: Check for file changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            frontend/**
            .github/workflows/frontend-ci.yml

      - name: Checkout repository
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/checkout@v4

      - name: Set up Node.js 24.7.0
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "24.7.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci

      - name: Run build
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run build
